### ISSUE TITLE
files not uploaded

### ISSUE THREAD

**Issue by doutriaux1** [conda-forge/mesalib-feedstock#13]
Issue: Even though all test come back "green" files are not being uploaded to anaconda

Environment: ALL

**Comment by doutriaux1** [comment]
@conda-forge-admin any idea why it is not uploading?

**Comment by mbargull** [comment]
> @conda-forge-admin any idea why it is not uploading?

You'll want to ping @conda-forge/core, the other one is just a bot :wink:.

@isuruf, I think this could be https://github.com/conda/conda-build/pull/2949 again, right?

**Comment by isuruf** [comment]
You should remove py3k from the skip statement and rerender.

**Comment by doutriaux1** [comment]
@isuruf but I think the install fails on Py3, their package has not been ported to Py3.

**Comment by CJ-Wright** [comment]
Is this a python package? There doesn't seem to be python in the dependencies.

**Comment by doutriaux1** [comment]
@CJ-Wright it's not but I think their installer uses Python, double-checking this at: #14

**Comment by matthiasdiener** [comment]
This appears to be not an issue anymore.
