### ISSUE TITLE
color channel size

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/mesalib-feedstock#22]
Is there any possibility to build with 8-bit-color channel additionally?

```bash
    --with-osmesa-bits=8
```
Currently this is built with 32-bit color channel only, which provides libOSMesa32.so, but downstream (vispy) we need libOSMesa.so. Thanks for looking into this.

**Comment by doutriaux1** [comment]
@kmuehlbauer yes definitely, we're having issues with mac at the moment though... Please fee free to issue a PR it will fasten things.

**Comment by kmuehlbauer** [comment]
@doutriaux1 This need some thinking. Can we build these libs after one another or are they exclusive? Unfortunately I have not that much insight into this.

**Comment by doutriaux1** [comment]
Good question, we could use a `feature` in the worst case. Right now we have `mesalib` but we could build we `mesalib8` feature worst case. I'll try to get to this, but I'm very short on time for this unfortunately.

**Comment by kmuehlbauer** [comment]
@doutriaux1 No worries, I'll try to poke around a bit.

**Comment by matthiasdiener** [comment]
Should we close this bug since #37 etc. have been merged?

**Comment by kmuehlbauer** [comment]
It's not a bug, more a feature request. But yes, we can close it for now.
