### ISSUE TITLE
color channel size change in recent pr

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/mesalib-feedstock#37]
@matthiasdiener was there a reason you decided to build with 8 bit channels instead of 32?

Is this something we could revert? Should we build both?

https://github.com/conda-forge/mesalib-feedstock/pull/34/files

**Comment by matthiasdiener** [comment]
Not sure, this change was taken from the "original" PR at #30. We might want to try building both, like you suggested.

**Comment by hmaarrfk** [comment]
I'm not sure i can find an example of people building with 32 bit support on a standard distribution.

I looked through what i think is Ubuntu's recipe and Fedora's
https://src.fedoraproject.org/rpms/mesa/blob/rawhide/f/mesa.spec#_343

Even arch doesn't seem to specify mesa-bits
https://github.com/archlinux/svntogit-packages/blob/packages/mesa/trunk/PKGBUILD#L44


maybe we should just remove it.

**Comment by hmaarrfk** [comment]
For what its worth, the defautl "bits" seems to be 8
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/meson_options.txt#L410

**Comment by kmuehlbauer** [comment]
@hmaarrfk @matthiasdiener  What's the difference anyway for libraries using mesalib, like vispy?

**Comment by hmaarrfk** [comment]
i'm really not sure. I forget why I needed newer mesalib. Maybe for a downstream package that needed it.

Honestly, I think that with the newer stuff we are more in line with what main stream distributions do. Do you need 32 bit? it seemed like you wanted 8 bit a while back ;)

https://github.com/conda-forge/mesalib-feedstock/issues/22

**Comment by kmuehlbauer** [comment]
Yeah, but I can't remember why.  :grimacing: At vispy we were in the transition from travis to github and from very old self compiled libOSMesa to conda-forge libOSMesa for use in CI. Nevertheless the older 32 bit channel lib works but the new 8bit channel does not. We also do not know if a new 32bit version would work. 

We did not change anything lately with regard to vispy's osmesa backend. But good chance that some things on the cython -side did change with the newer mesalib. Any hints how to debug?

**Comment by hmaarrfk** [comment]
I might start by building your own conda packages, built with differetn options. You can use build numbers to specify different ones. Uploaded to your own independent channel. you can use `python build-locally.py` to help build quickly. Any decent machine should build these in under 10 mins.

**Comment by kmuehlbauer** [comment]
Thanks Mark, I'm trying to set up a local conda channel and see how this goes.

**Comment by hmaarrfk** [comment]
I guess we also updated minimum centos version from 6 to 7 but conda should pick that up automatically.
